import { NextResponse } from "next/server";

export async function GET() {
  const businessAreas = [
    {
      value: "academia, crossfit, treinamento-funcional",
      label: "Academia, Crossfit, Treinamento Funcional",
    },
    { value: "artes-marciais", label: "Artes Marciais" },
    { value: "clube-esportivo", label: "Clube Esportivo / Associação" },
    { value: "time-futebol-futsal", label: "Time de Futebol / Futsal" },
    { value: "restaurante", label: "Restaurante" },
    { value: "bar-pub", label: "Bar / Pub" },
    { value: "cafeteria", label: "Cafeteria" },
    { value: "padaria", label: "Padaria / Confeitaria" },
    { value: "food-truck", label: "Food Truck" },
    { value: "cervejaria", label: "Cervejaria / Bar Artesanal" },
    { value: "sorveteria", label: "Sorveteria" },
    { value: "clinica", label: "Clínica Médica" },
    { value: "clinica-odontologica", label: "Clínica Odontológica" },
    { value: "estetica", label: "Estética / Spa" },
    { value: "barbearia", label: "Barbearia" },
    { value: "salao-de-beleza", label: "Salão de Beleza" },
    { value: "farmacia", label: "Farmácia / Drogaria" },
    { value: "veterinaria-pet-shop", label: "Veterinária / Pet Shop" },
    {
      value: "filmagem-fotografia-design-ilustracao",
      label: "Filmagem / Fotografia / Design / Ilustração",
    },
    { value: "producao-de-eventos", label: "Eventos / Produção" },
    { value: "musica-bandas", label: "Música / Bandas / Artistas" },
    { value: "agencia-marketing", label: "Agência de Marketing / Publicidade" },
    {
      value: "influenciadores",
      label: "Influenciadores / Criadores de Conteúdo",
    },
    { value: "tecnologia", label: "Tecnologia / Software" },
    { value: "ecommerce", label: "E-commerce" },
    { value: "startup", label: "Startup" },
    { value: "varejo-moda", label: "Varejo / Moda" },
    { value: "loja-esportiva", label: "Loja de Artigos Esportivos" },
    { value: "shopping", label: "Shopping / Centro Comercial" },
    { value: "industria-textil", label: "Indústria Têxtil" },
    { value: "industria-geral", label: "Indústria (Geral)" },
    { value: "metalurgica", label: "Metalúrgica" },
    { value: "construcao-civil", label: "Construção Civil" },
    { value: "imobiliaria", label: "Imobiliária" },
    { value: "arquitetura", label: "Arquitetura" },
    { value: "engenharia", label: "Engenharia" },
    { value: "marcenaria", label: "Marcenaria / Móveis" },
    { value: "vidracaria", label: "Vidraçaria" },
    { value: "marmoraria", label: "Marmoraria" },
    { value: "logistica", label: "Logística / Transportes" },
    { value: "moto-entrega", label: "Moto Entrega / Delivery" },
    { value: "autopecas", label: "Autopeças" },
    { value: "oficina-mecanica", label: "Oficina Mecânica" },
    { value: "concessionaria", label: "Concessionária" },
    { value: "agronegocio", label: "Agronegócio" },
    { value: "floricultura", label: "Floricultura" },
    { value: "jardinagem", label: "Jardinagem / Paisagismo" },
    { value: "energia-solar", label: "Energia Solar" },
    { value: "eletrica", label: "Elétrica / Instalações" },
    { value: "telecom", label: "Telecomunicações / Internet" },
    { value: "escola", label: "Escola / Colégio" },
    { value: "faculdade", label: "Faculdade / Universidade" },
    { value: "cursos", label: "Cursos / Treinamentos" },
    { value: "idiomas", label: "Escola de Idiomas" },
    { value: "igreja", label: "Igreja / Organização Religiosa" },
    { value: "ong", label: "ONG / Terceiro Setor" },
    { value: "governo", label: "Órgãos Públicos / Governo" },
    { value: "seguranca", label: "Segurança / Portaria" },
    { value: "limpeza", label: "Limpeza / Serviços Gerais" },
    { value: "manutencao", label: "Manutenção Predial" },
    { value: "hotelaria", label: "Hotelaria / Pousada" },
    { value: "turismo", label: "Turismo / Agência de Viagens" },
    { value: "rh-consultoria", label: "RH / Consultoria" },
    { value: "contabilidade", label: "Contabilidade" },
    { value: "advocacia", label: "Advocacia" },
    { value: "seguros", label: "Seguros / Corretora" },
    { value: "cartorio", label: "Cartório" },
    { value: "brindes-corporativos", label: "Brindes Corporativos" },
    { value: "representantes-comerciais", label: "Representantes Comerciais" },
    { value: "franquias", label: "Franquias" },
    { value: "outro", label: "Outro" },
  ];

  return NextResponse.json(businessAreas);
}
